# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0006_auto_20160924_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='landr.Register'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='landr.Register'),
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokes',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokes',
            field=models.IntegerField(default=0),
        ),
    ]
