# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0007_auto_20160926_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='poke_total',
            field=models.IntegerField(default=0),
        ),
    ]
