# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0009_auto_20160927_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='poke_total',
        ),
        migrations.AddField(
            model_name='user',
            name='bday',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
