# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20160927_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
