# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landr', '0010_auto_20160927_0840'),
        ('wishlist', '0003_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(to='landr.User'),
        ),
    ]
